/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */


import type { core } from "nexus"
declare global {
  interface NexusGenCustomInputMethods<TypeName extends string> {
    /**
     * A custom scalar type representing a date and time.
     */
    date<FieldName extends string>(fieldName: FieldName, opts?: core.CommonInputFieldConfig<TypeName, FieldName>): void // "DateTime";
  }
}
declare global {
  interface NexusGenCustomOutputMethods<TypeName extends string> {
    /**
     * A custom scalar type representing a date and time.
     */
    date<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "DateTime";
  }
}


declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
}

export interface NexusGenEnums {
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
  DateTime: any
}

export interface NexusGenObjects {
  Comment: { // root type
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    id?: string | null; // String
    text?: string | null; // String
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  Edge: { // root type
    cursor?: string | null; // String
    node?: NexusGenRootTypes['Post'] | null; // Post
  }
  Me: { // root type
    email?: string | null; // String
    fullname?: string | null; // String
    iamge?: string | null; // String
    name?: string | null; // String
    userId?: string | null; // String
  }
  Mutation: {};
  PageInfo: { // root type
    endCursor?: string | null; // String
    hasNextPage?: boolean | null; // Boolean
  }
  Post: { // root type
    caption?: string | null; // String
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    id?: string | null; // String
    imageUrl?: string | null; // String
    likesCount?: number | null; // Int
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  Query: {};
  Response: { // root type
    edges?: Array<NexusGenRootTypes['Edge'] | null> | null; // [Edge]
    pageInfo?: NexusGenRootTypes['PageInfo'] | null; // PageInfo
  }
  Session: { // root type
    accessToken?: string | null; // String
    email?: string | null; // String
    fullname?: string | null; // String
    iamge?: string | null; // String
    name?: string | null; // String
    userId?: string | null; // String
  }
  User: { // root type
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    email?: string | null; // String
    fullname?: string | null; // String
    iamge?: string | null; // String
    id?: string | null; // String
    name?: string | null; // String
    password?: string | null; // String
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars

export interface NexusGenFieldTypes {
  Comment: { // field return type
    author: NexusGenRootTypes['User'] | null; // User
    createdAt: NexusGenScalars['DateTime'] | null; // DateTime
    id: string | null; // String
    post: NexusGenRootTypes['Post'] | null; // Post
    text: string | null; // String
    updatedAt: NexusGenScalars['DateTime'] | null; // DateTime
  }
  Edge: { // field return type
    cursor: string | null; // String
    node: NexusGenRootTypes['Post'] | null; // Post
  }
  Me: { // field return type
    email: string | null; // String
    fullname: string | null; // String
    iamge: string | null; // String
    name: string | null; // String
    userId: string | null; // String
  }
  Mutation: { // field return type
    createPost: NexusGenRootTypes['Post'] | null; // Post
    deletePost: NexusGenRootTypes['Post'] | null; // Post
    likePost: NexusGenRootTypes['Post'] | null; // Post
    login: NexusGenRootTypes['Session']; // Session!
    register: NexusGenRootTypes['User']; // User!
    unlikePost: NexusGenRootTypes['Post'] | null; // Post
  }
  PageInfo: { // field return type
    endCursor: string | null; // String
    hasNextPage: boolean | null; // Boolean
  }
  Post: { // field return type
    author: NexusGenRootTypes['User'] | null; // User
    caption: string | null; // String
    comments: Array<NexusGenRootTypes['Comment'] | null> | null; // [Comment]
    createdAt: NexusGenScalars['DateTime'] | null; // DateTime
    id: string | null; // String
    imageUrl: string | null; // String
    likesCount: number | null; // Int
    updatedAt: NexusGenScalars['DateTime'] | null; // DateTime
  }
  Query: { // field return type
    getAllPosts: Array<NexusGenRootTypes['Post'] | null> | null; // [Post]
    getPost: NexusGenRootTypes['Post'] | null; // Post
    getUserById: NexusGenRootTypes['User'] | null; // User
    getUsers: Array<NexusGenRootTypes['User'] | null> | null; // [User]
    me: NexusGenRootTypes['Me'] | null; // Me
    posts: NexusGenRootTypes['Response'] | null; // Response
  }
  Response: { // field return type
    edges: Array<NexusGenRootTypes['Edge'] | null> | null; // [Edge]
    pageInfo: NexusGenRootTypes['PageInfo'] | null; // PageInfo
  }
  Session: { // field return type
    accessToken: string | null; // String
    email: string | null; // String
    fullname: string | null; // String
    iamge: string | null; // String
    name: string | null; // String
    userId: string | null; // String
  }
  User: { // field return type
    createdAt: NexusGenScalars['DateTime'] | null; // DateTime
    email: string | null; // String
    followers: Array<NexusGenRootTypes['User'] | null> | null; // [User]
    following: Array<NexusGenRootTypes['User'] | null> | null; // [User]
    fullname: string | null; // String
    iamge: string | null; // String
    id: string | null; // String
    name: string | null; // String
    password: string | null; // String
    posts: Array<NexusGenRootTypes['Post'] | null> | null; // [Post]
    updatedAt: NexusGenScalars['DateTime'] | null; // DateTime
  }
}

export interface NexusGenFieldTypeNames {
  Comment: { // field return type name
    author: 'User'
    createdAt: 'DateTime'
    id: 'String'
    post: 'Post'
    text: 'String'
    updatedAt: 'DateTime'
  }
  Edge: { // field return type name
    cursor: 'String'
    node: 'Post'
  }
  Me: { // field return type name
    email: 'String'
    fullname: 'String'
    iamge: 'String'
    name: 'String'
    userId: 'String'
  }
  Mutation: { // field return type name
    createPost: 'Post'
    deletePost: 'Post'
    likePost: 'Post'
    login: 'Session'
    register: 'User'
    unlikePost: 'Post'
  }
  PageInfo: { // field return type name
    endCursor: 'String'
    hasNextPage: 'Boolean'
  }
  Post: { // field return type name
    author: 'User'
    caption: 'String'
    comments: 'Comment'
    createdAt: 'DateTime'
    id: 'String'
    imageUrl: 'String'
    likesCount: 'Int'
    updatedAt: 'DateTime'
  }
  Query: { // field return type name
    getAllPosts: 'Post'
    getPost: 'Post'
    getUserById: 'User'
    getUsers: 'User'
    me: 'Me'
    posts: 'Response'
  }
  Response: { // field return type name
    edges: 'Edge'
    pageInfo: 'PageInfo'
  }
  Session: { // field return type name
    accessToken: 'String'
    email: 'String'
    fullname: 'String'
    iamge: 'String'
    name: 'String'
    userId: 'String'
  }
  User: { // field return type name
    createdAt: 'DateTime'
    email: 'String'
    followers: 'User'
    following: 'User'
    fullname: 'String'
    iamge: 'String'
    id: 'String'
    name: 'String'
    password: 'String'
    posts: 'Post'
    updatedAt: 'DateTime'
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    createPost: { // args
      caption?: string | null; // String
      imageUrl: string; // String!
    }
    deletePost: { // args
      id: string; // String!
    }
    likePost: { // args
      id: string; // String!
    }
    login: { // args
      email: string; // String!
      password: string; // String!
    }
    register: { // args
      email: string; // String!
      fullname?: string | null; // String
      name?: string | null; // String
      password: string; // String!
    }
    unlikePost: { // args
      id: string; // String!
    }
  }
  Query: {
    getPost: { // args
      id: string; // ID!
    }
    getUserById: { // args
      id: string; // ID!
    }
    posts: { // args
      after?: string | null; // String
      first?: number | null; // Int
    }
  }
}

export interface NexusGenAbstractTypeMembers {
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = never;

export type NexusGenEnumNames = never;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: any;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginInputTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}